remote: origin
target-branch: main
helm-extra-args: --timeout 600s
chart-dirs:
- charts/incubator
- charts/stable
chart-repos:
- k8s-at-home-libraries=https://rolfberkenbosch.github.io/library-charts/
